/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelloImport } from './routes/hello'

// Create/Update Routes

const HelloRoute = HelloImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/hello': typeof HelloRoute
}

export interface FileRoutesByTo {
  '/hello': typeof HelloRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/hello': typeof HelloRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/hello'
  fileRoutesByTo: FileRoutesByTo
  to: '/hello'
  id: '__root__' | '/hello'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HelloRoute: typeof HelloRoute
}

const rootRouteChildren: RootRouteChildren = {
  HelloRoute: HelloRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/hello"
      ]
    },
    "/hello": {
      "filePath": "hello.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
